import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/src/styles/Home.module.css";
import { Header } from "@/src/components/Header";
import { ALBUM_PAGE_TITLE } from "@/src/utils/path";
import { Footer } from "@/src/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const title = ALBUM_PAGE_TITLE;
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header title={title} />
        <div>Album</div>
        <Footer />
      </main>
    </>
  );
}
