import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/src/styles/Home.module.css";
// import { Header } from "@/src/components/Header";
import { EVENTS_PROPS } from "@/src/utils/path";
import { Box, Typography } from "@mui/material";
import { Header } from "@/src/components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function EventDetailPage() {
  const title = EVENTS_PROPS[3].eventTitle;
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header title={title} />
        <Box
          sx={{
            width: "100%",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}>
          <div>日程</div>
          <Typography sx={{ width: "800px", alignItems: "left" }}>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quaerat
            enim quas doloremque repellat incidunt amet, ducimus numquam iste
            itaque vero possimus consequatur animi excepturi facilis dolores
            quia non atque maiores?
          </Typography>
          <div>内容</div>
          <div>場所</div>
          <div>時間</div>
          <div>アクセス</div>
          <div>地図</div>
        </Box>
      </main>
    </>
  );
}
