import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/src/styles/Home.module.css";
import { Header } from "@/src/components/Header";
import { INDEX_PAGE_TITLE } from "@/src/utils/path";
import { Footer } from "@/src/components/Footer";
import { Box, Button, Typography } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const title = INDEX_PAGE_TITLE;
  const DEMO_LIST = [
    "ああああああ",
    "いいいいいい",
    "うううううう",
    "ええええええ",
    "おおおおおお",
  ];
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header title={title} />
        <Box
          sx={{
            display: "flex",
            flexDirection: "column",
          }}>
          {DEMO_LIST.map((text) => {
            return (
              <Typography
                sx={{
                  marginBottom: "4px",
                  "&::before": {
                    background: "green",
                    content: '"iii"',
                    borderBottom: "1px solid white",
                    marginRight: "20px",
                  },
                }}>
                {text}
              </Typography>
            );
          })}
        </Box>
        <Button
          sx={{ backgroundColor: "white", marginTop: "2rem" }}
          onClick={(event) => {
            event.preventDefault;
            alert(event.target.href);
          }}>
          ボタン
        </Button>
        <Footer />
      </main>
    </>
  );
}
