import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { DocsGrid } from "@/components/DocsGrid";
import { NextImage } from "@/components/NextImage";
import { Header } from "@/components/Header";
import { ABOUT_PAGE_TITLE } from "@/utils/path";
import { Footer } from "@/components/Footer";
import { Container, Typography } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const title = ABOUT_PAGE_TITLE;
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header title={title} />
        <Container
          sx={{
            display: "flex",
            justifyContent: "center",
            backgroundColor: "gray",
            padding: "30px 0",
          }}>
          <Typography sx={{ width: "50%" }}>
            えーーー、このページは、、、そうすね <br />
            フロント側での作業を勉強するのを兼ねて、作ってみてます。 <br />
            機能とかを学びながらつけたりしています。 <br />
            勉強で知ったやつをとりあえず、つけてみてますので、ダサいです😂
            <br />
            一応公開してはいますが、
            <br />
            顔の写真をなるべくつけないようにしていきます。
            <br />
          </Typography>
        </Container>
        <Footer />
      </main>
    </>
  );
}
