import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import stylesAA from "../components/AAA.module.css";
import { DocsGrid } from "@/components/DocsGrid";
import { Header } from "@/components/Header";
import { EVENT_PAGE_TITLE } from "@/utils/path";
import { Container, List, ListItem, Typography } from "@mui/material";
import Image from "next/image";
import Link from "next/link";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const title = EVENT_PAGE_TITLE;
  const pageColor = `radial-gradient(circle, rgba(238,174,202,1) 0%, rgba(148,187,233,1) 100%)`;
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header title={title} color={pageColor} />
        <h2>EVENT</h2>
        <Container
          sx={{
            display: "flex",
            justifyContent: "flex-start",
            flexDirection: "column",
          }}>
          <Typography
            component="h2"
            sx={{ fontSize: "2rem", fontWeight: "bold" }}>
            CALENDER
          </Typography>

          <Link href="AAA">
            <div
              className={stylesAA.AAA}
              style={{
                color: "white",
                display: "flex",
                borderBottom: "1px solid white",
                alignItems: "center",
                height: "45px",
                padding: "0 20px",
              }}>
              <div style={{ width: "20%" }}>2020.01.01（月）</div>
              <div style={{ width: "30%" }}>鎌倉 - 江ノ島</div>
            </div>
          </Link>

          <Image
            src="/AAA.png"
            alt="border"
            width={1}
            height={150}
            style={{ marginTop: "30px" }}
          />
          <Link href="AAA">
            <div
              className={stylesAA.AAA}
              style={{
                color: "white",
                display: "flex",
                borderBottom: "1px solid white",
                alignItems: "center",
                height: "45px",
                padding: "0 20px",
              }}>
              <div style={{ width: "20%" }}>2023.08.19 （土）</div>
              <div style={{ width: "30%" }}>鎌倉 - 江ノ島</div>
            </div>
          </Link>
          <Image
            src="/AAA.png"
            alt="border"
            width={1}
            height={150}
            style={{ marginTop: "30px" }}
          />
          <Link href="AAA">
            <div
              className={stylesAA.AAA}
              style={{
                color: "white",
                display: "flex",
                borderBottom: "1px solid white",
                alignItems: "center",
                height: "45px",
                padding: "20px",
                ":hover": { borderLeft: "1px solid white" },
              }}>
              <div style={{ width: "20%" }}>2023.08.19 （土）</div>
              <div style={{ width: "30%" }}>越谷レイクタウン VsPark</div>
            </div>
          </Link>
        </Container>
        <Footer />
      </main>
    </>
  );
}
